// GENERATED by scripts/gen-api-reference.py in
// https://github.com/ValeryVerkhoturov/wb-api-client — do not edit.
// Sidebar for the endpoint reference: one collapsed group per API
// module, one entry per operation.

import type { DefaultTheme } from "vitepress";

export const apiSidebar: Record<string, DefaultTheme.SidebarItem[]> = {
  ru: [
    {
      text: "Справочник API",
      link: "/reference/api/",
    },
    {
      text: "Общее · general",
      collapsed: true,
      items: [
        {
          text: "Проверка подключения",
          link: "/reference/api/general/get-ping",
        },
        {
          text: "Получение новостей портала продавцов",
          link: "/reference/api/general/get-api-communications-v2-news",
        },
        {
          text: "Получить информацию о продавце",
          link: "/reference/api/general/get-api-v1-seller-info",
        },
        {
          text: "Получить рейтинг продавца",
          link: "/reference/api/general/get-api-common-v1-rating",
        },
        {
          text: "Получить информацию о подписке Джем",
          link: "/reference/api/general/get-api-common-v1-subscriptions",
        },
        {
          text: "Получить информацию об опциях Конструктора тарифов",
          link: "/reference/api/general/get-api-common-v1-tariff-constructor-options",
        },
        {
          text: "Создать приглашение для нового пользователя",
          link: "/reference/api/general/post-api-v1-invite",
        },
        {
          text: "Получить список активных или приглашённых пользователей продавца",
          link: "/reference/api/general/get-api-v1-users",
        },
        {
          text: "Изменить права доступа пользователей",
          link: "/reference/api/general/put-api-v1-users-access",
        },
        {
          text: "Удалить пользователя",
          link: "/reference/api/general/delete-api-v1-user",
        },
      ],
    },
    {
      text: "Работа с товарами · items",
      collapsed: true,
      items: [
        {
          text: "Родительские категории товаров",
          link: "/reference/api/items/get-content-v2-object-parent-all",
        },
        {
          text: "Список предметов",
          link: "/reference/api/items/get-content-v2-object-all",
        },
        {
          text: "Характеристики предмета",
          link: "/reference/api/items/get-content-v2-object-charcs-subjectid",
        },
        {
          text: "Цвет",
          link: "/reference/api/items/get-content-v2-directory-colors",
        },
        {
          text: "Пол",
          link: "/reference/api/items/get-content-v2-directory-kinds",
        },
        {
          text: "Страна производства",
          link: "/reference/api/items/get-content-v2-directory-countries",
        },
        {
          text: "Сезон",
          link: "/reference/api/items/get-content-v2-directory-seasons",
        },
        {
          text: "Ставка НДС",
          link: "/reference/api/items/get-content-v2-directory-vat",
        },
        {
          text: "Код ТН ВЭД предмета",
          link: "/reference/api/items/get-content-v2-directory-tnved",
        },
        {
          text: "Список кодов ТН ВЭД",
          link: "/reference/api/items/get-api-content-v2-directory-tnved-all",
        },
        {
          text: "Код ОКПД2 предмета",
          link: "/reference/api/items/get-api-content-v2-directory-okpd",
        },
        {
          text: "Список кодов ОКПД2",
          link: "/reference/api/items/get-api-content-v2-directory-okpd-all",
        },
        {
          text: "Бренды",
          link: "/reference/api/items/get-api-content-v1-brands",
        },
        {
          text: "Список ярлыков",
          link: "/reference/api/items/get-content-v2-tags",
        },
        {
          text: "Создание ярлыка",
          link: "/reference/api/items/post-content-v2-tag",
        },
        {
          text: "Изменение ярлыка",
          link: "/reference/api/items/patch-content-v2-tag-id",
        },
        {
          text: "Удаление ярлыка",
          link: "/reference/api/items/delete-content-v2-tag-id",
        },
        {
          text: "Управление ярлыками в карточке товара",
          link: "/reference/api/items/post-content-v2-tag-nomenclature-link",
        },
        {
          text: "Список карточек товаров",
          link: "/reference/api/items/post-content-v2-get-cards-list",
        },
        {
          text: "Список несозданных карточек товаров с ошибками",
          link: "/reference/api/items/post-content-v2-cards-error-list",
        },
        {
          text: "Редактирование карточек товаров",
          link: "/reference/api/items/post-content-v2-cards-update",
        },
        {
          text: "Объединение и разъединение карточек товаров",
          link: "/reference/api/items/post-content-v2-cards-movenm",
        },
        {
          text: "Перенос карточек товаров в корзину",
          link: "/reference/api/items/post-content-v2-cards-delete-trash",
        },
        {
          text: "Восстановление карточек товаров из корзины",
          link: "/reference/api/items/post-content-v2-cards-recover",
        },
        {
          text: "Список карточек товаров в корзине",
          link: "/reference/api/items/post-content-v2-get-cards-trash",
        },
        {
          text: "Лимиты карточек товаров",
          link: "/reference/api/items/get-content-v2-cards-limits",
        },
        {
          text: "Генерация баркодов",
          link: "/reference/api/items/post-content-v2-barcodes",
        },
        {
          text: "Создание карточек товаров",
          link: "/reference/api/items/post-content-v2-cards-upload",
        },
        {
          text: "Создание карточек товаров с присоединением",
          link: "/reference/api/items/post-content-v2-cards-upload-add",
        },
        {
          text: "Загрузить медиафайл",
          link: "/reference/api/items/post-content-v3-media-file",
        },
        {
          text: "Загрузить медиафайлы по ссылкам",
          link: "/reference/api/items/post-content-v3-media-save",
        },
        {
          text: "Список рекомендаций в карточках товаров",
          link: "/reference/api/items/post-api-content-v1-recommendations-list",
        },
        {
          text: "Установить рекомендации для товаров",
          link: "/reference/api/items/post-api-content-v1-recommendations-set",
        },
        {
          text: "Установить цены и скидки",
          link: "/reference/api/items/post-api-v2-upload-task",
        },
        {
          text: "Установить цены для размеров",
          link: "/reference/api/items/post-api-v2-upload-task-size",
        },
        {
          text: "Установить скидки WB Клуба",
          link: "/reference/api/items/post-api-v2-upload-task-club-discount",
        },
        {
          text: "Установить оптовые скидки для B2B-продаж",
          link: "/reference/api/items/post-api-discounts-prices-v1-upload-task-b2b-wholesale",
        },
        {
          text: "Состояние обработанной загрузки",
          link: "/reference/api/items/get-api-v2-history-tasks",
        },
        {
          text: "Детализация обработанной загрузки",
          link: "/reference/api/items/get-api-v2-history-goods-task",
        },
        {
          text: "Состояние необработанной загрузки",
          link: "/reference/api/items/get-api-v2-buffer-tasks",
        },
        {
          text: "Детализация необработанной загрузки",
          link: "/reference/api/items/get-api-v2-buffer-goods-task",
        },
        {
          text: "Получить товары с ценами",
          link: "/reference/api/items/get-api-v2-list-goods-filter",
        },
        {
          text: "Получить товары с ценами по артикулам",
          link: "/reference/api/items/post-api-v2-list-goods-filter",
        },
        {
          text: "Получить размеры товара с ценами",
          link: "/reference/api/items/get-api-v2-list-goods-size-nm",
        },
        {
          text: "Получить товары в карантине",
          link: "/reference/api/items/get-api-v2-quarantine-goods",
        },
        {
          text: "Обновить остатки товаров",
          link: "/reference/api/items/put-api-v3-stocks-warehouseid",
        },
        {
          text: "Удалить остатки товаров",
          link: "/reference/api/items/delete-api-v3-stocks-warehouseid",
        },
        {
          text: "Получить остатки товаров",
          link: "/reference/api/items/post-api-v3-stocks-warehouseid",
        },
        {
          text: "Получить список складов WB",
          link: "/reference/api/items/get-api-v3-offices",
        },
        {
          text: "Получить список складов продавца",
          link: "/reference/api/items/get-api-v3-warehouses",
        },
        {
          text: "Создать склад продавца",
          link: "/reference/api/items/post-api-v3-warehouses",
        },
        {
          text: "Обновить склад продавца",
          link: "/reference/api/items/put-api-v3-warehouses-warehouseid",
        },
        {
          text: "Удалить склад продавца",
          link: "/reference/api/items/delete-api-v3-warehouses-warehouseid",
        },
        {
          text: "Список контактов",
          link: "/reference/api/items/get-api-v3-dbw-warehouses-warehouseid-contacts",
        },
        {
          text: "Обновить список контактов",
          link: "/reference/api/items/put-api-v3-dbw-warehouses-warehouseid-contacts",
        },
      ],
    },
    {
      text: "Заказы FBS · orders-fbs",
      collapsed: true,
      items: [
        {
          text: "Получить список складов, для которых требуется пропуск",
          link: "/reference/api/orders-fbs/get-api-v3-passes-offices",
        },
        {
          text: "Получить список пропусков",
          link: "/reference/api/orders-fbs/get-api-v3-passes",
        },
        {
          text: "Создать пропуск",
          link: "/reference/api/orders-fbs/post-api-v3-passes",
        },
        {
          text: "Обновить пропуск",
          link: "/reference/api/orders-fbs/put-api-v3-passes-passid",
        },
        {
          text: "Удалить пропуск",
          link: "/reference/api/orders-fbs/delete-api-v3-passes-passid",
        },
        {
          text: "Получить список новых сборочных заданий",
          link: "/reference/api/orders-fbs/get-api-v3-orders-new",
        },
        {
          text: "Получить информацию о сборочных заданиях",
          link: "/reference/api/orders-fbs/get-api-v3-orders",
        },
        {
          text: "Получить статусы сборочных заданий",
          link: "/reference/api/orders-fbs/post-api-v3-orders-status",
        },
        {
          text: "Получить все сборочные задания для повторной отгрузки",
          link: "/reference/api/orders-fbs/get-api-v3-supplies-orders-reshipment",
        },
        {
          text: "Отменить сборочное задание",
          link: "/reference/api/orders-fbs/patch-api-v3-orders-orderid-cancel",
        },
        {
          text: "Получить стикеры сборочных заданий",
          link: "/reference/api/orders-fbs/post-api-v3-orders-stickers",
        },
        {
          text: "Получить стикеры сборочных заданий трансграничных поставок",
          link: "/reference/api/orders-fbs/post-api-v3-orders-stickers-cross-border",
        },
        {
          text: "История статусов для сборочных заданий трансграничных поставок",
          link: "/reference/api/orders-fbs/post-api-v3-orders-status-history",
        },
        {
          text: "Заказы с информацией по клиенту",
          link: "/reference/api/orders-fbs/post-api-v3-orders-client",
        },
        {
          text: "Получить список архивных сборочных заданий",
          link: "/reference/api/orders-fbs/get-api-marketplace-v3-fbs-orders-archive",
        },
        {
          text: "Получить идентификаторы маркировки сборочных заданий",
          link: "/reference/api/orders-fbs/post-api-marketplace-v3-orders-meta",
        },
        {
          text: "Удалить идентификаторы маркировки сборочного задания",
          link: "/reference/api/orders-fbs/delete-api-v3-orders-orderid-meta",
        },
        {
          text: "Закрепить код маркировки Честного знака за сборочным заданием",
          link: "/reference/api/orders-fbs/put-api-v3-orders-orderid-meta-sgtin",
        },
        {
          text: "Закрепить УИН за сборочным заданием",
          link: "/reference/api/orders-fbs/put-api-v3-orders-orderid-meta-uin",
        },
        {
          text: "Закрепить IMEI за сборочным заданием",
          link: "/reference/api/orders-fbs/put-api-v3-orders-orderid-meta-imei",
        },
        {
          text: "Закрепить GTIN за сборочным заданием",
          link: "/reference/api/orders-fbs/put-api-v3-orders-orderid-meta-gtin",
        },
        {
          text: "Закрепить за сборочным заданием срок годности товара",
          link: "/reference/api/orders-fbs/put-api-v3-orders-orderid-meta-expiration",
        },
        {
          text: "Закрепить номер ДТ за сборочным заданием",
          link: "/reference/api/orders-fbs/put-api-marketplace-v3-orders-orderid-meta-customs-declaration",
        },
        {
          text: "Создать новую поставку",
          link: "/reference/api/orders-fbs/post-api-v3-supplies",
        },
        {
          text: "Получить список поставок",
          link: "/reference/api/orders-fbs/get-api-v3-supplies",
        },
        {
          text: "Добавить сборочные задания к поставке",
          link: "/reference/api/orders-fbs/patch-api-marketplace-v3-supplies-supplyid-orders",
        },
        {
          text: "Получить информацию о поставке",
          link: "/reference/api/orders-fbs/get-api-v3-supplies-supplyid",
        },
        {
          text: "Удалить поставку",
          link: "/reference/api/orders-fbs/delete-api-v3-supplies-supplyid",
        },
        {
          text: "Получить ID сборочных заданий поставки",
          link: "/reference/api/orders-fbs/get-api-marketplace-v3-supplies-supplyid-order-ids",
        },
        {
          text: "Получить список пунктов отгрузки поставок",
          link: "/reference/api/orders-fbs/get-api-marketplace-v3-fbs-shipping-points",
        },
        {
          text: "Установить параметры отгрузки поставок",
          link: "/reference/api/orders-fbs/patch-api-marketplace-v3-fbs-supplies-shipping-method",
        },
        {
          text: "Установить ID ЭТрН поставок",
          link: "/reference/api/orders-fbs/patch-api-marketplace-v3-fbs-supplies-waybill",
        },
        {
          text: "Передать поставку в доставку",
          link: "/reference/api/orders-fbs/patch-api-v3-supplies-supplyid-deliver",
        },
        {
          text: "Получить QR-код поставки",
          link: "/reference/api/orders-fbs/get-api-v3-supplies-supplyid-barcode",
        },
        {
          text: "Получить список грузомест поставки",
          link: "/reference/api/orders-fbs/get-api-v3-supplies-supplyid-trbx",
        },
        {
          text: "Добавить грузоместа к поставке",
          link: "/reference/api/orders-fbs/post-api-v3-supplies-supplyid-trbx",
        },
        {
          text: "Удалить грузоместа из поставки",
          link: "/reference/api/orders-fbs/delete-api-v3-supplies-supplyid-trbx",
        },
        {
          text: "Получить стикеры грузомест поставки",
          link: "/reference/api/orders-fbs/post-api-v3-supplies-supplyid-trbx-stickers",
        },
        {
          text: "Получить список стран ОКСМ",
          link: "/reference/api/orders-fbs/get-api-marketplace-v3-fbs-dictionaries-countries-oksm",
        },
        {
          text: "Добавить данные СПОТ в поставку",
          link: "/reference/api/orders-fbs/put-api-marketplace-v3-fbs-supplies-supplyid-spot",
        },
        {
          text: "Получить данные СПОТ для списка поставок",
          link: "/reference/api/orders-fbs/post-api-marketplace-v3-fbs-supplies-spot-list",
        },
        {
          text: "Получить QR-код СПОТ",
          link: "/reference/api/orders-fbs/get-api-marketplace-v3-fbs-supplies-supplyid-stickers-spot",
        },
        {
          text: "Получить настройки автовозврата продавца",
          link: "/reference/api/orders-fbs/get-api-marketplace-v3-fbs-settings-autoreturns",
        },
        {
          text: "Обновить настройки автовозврата продавца",
          link: "/reference/api/orders-fbs/patch-api-marketplace-v3-fbs-settings-autoreturns",
        },
        {
          text: "Получить настройки автовозврата товаров",
          link: "/reference/api/orders-fbs/post-api-marketplace-v3-fbs-settings-autoreturns-items",
        },
        {
          text: "Обновить настройки автовозврата товаров",
          link: "/reference/api/orders-fbs/patch-api-marketplace-v3-fbs-settings-autoreturns-items",
        },
        {
          text: "Получить предметы, которые не хранятся на складах WB",
          link: "/reference/api/orders-fbs/get-api-marketplace-v3-fbs-settings-autoreturns-subcategories-restricted",
        },
      ],
    },
    {
      text: "Заказы DBW · orders-dbw",
      collapsed: true,
      items: [
        {
          text: "Получить список новых сборочных заданий",
          link: "/reference/api/orders-dbw/get-api-v3-dbw-orders-new",
        },
        {
          text: "Получить информацию о завершенных сборочных заданиях",
          link: "/reference/api/orders-dbw/get-api-v3-dbw-orders",
        },
        {
          text: "Получить дату и время доставки",
          link: "/reference/api/orders-dbw/post-api-v3-dbw-orders-delivery-date",
        },
        {
          text: "Информация о покупателе",
          link: "/reference/api/orders-dbw/post-api-marketplace-v3-dbw-orders-client",
        },
        {
          text: "Получить статусы сборочных заданий",
          link: "/reference/api/orders-dbw/post-api-v3-dbw-orders-status",
        },
        {
          text: "Перевести на сборку",
          link: "/reference/api/orders-dbw/patch-api-v3-dbw-orders-orderid-confirm",
        },
        {
          text: "Получить стикеры сборочных заданий",
          link: "/reference/api/orders-dbw/post-api-v3-dbw-orders-stickers",
        },
        {
          text: "Перевести сборочные задания в доставку",
          link: "/reference/api/orders-dbw/post-api-marketplace-v3-dbw-orders-status-deliver",
        },
        {
          text: "Информация о курьере",
          link: "/reference/api/orders-dbw/post-api-v3-dbw-orders-courier",
        },
        {
          text: "Отменить сборочное задание",
          link: "/reference/api/orders-dbw/patch-api-v3-dbw-orders-orderid-cancel",
        },
        {
          text: "Получить идентификаторы маркировки сборочных заданий",
          link: "/reference/api/orders-dbw/post-api-marketplace-v3-dbw-orders-meta-details",
        },
        {
          text: "Удалить идентификаторы маркировки сборочных заданий",
          link: "/reference/api/orders-dbw/post-api-marketplace-v3-dbw-orders-meta-delete",
        },
        {
          text: "Закрепить коды маркировки Честного знака за сборочными заданиями",
          link: "/reference/api/orders-dbw/post-api-marketplace-v3-dbw-orders-meta-sgtin",
        },
        {
          text: "Закрепить УИН за сборочным заданием",
          link: "/reference/api/orders-dbw/put-api-v3-dbw-orders-orderid-meta-uin",
        },
        {
          text: "Закрепить IMEI за сборочным заданием",
          link: "/reference/api/orders-dbw/put-api-v3-dbw-orders-orderid-meta-imei",
        },
        {
          text: "Закрепить GTIN за сборочным заданием",
          link: "/reference/api/orders-dbw/put-api-v3-dbw-orders-orderid-meta-gtin",
        },
      ],
    },
    {
      text: "DBS · dbs",
      collapsed: true,
      items: [
        {
          text: "Получить список новых сборочных заданий",
          link: "/reference/api/dbs/get-api-v3-dbs-orders-new",
        },
        {
          text: "Получить информацию о завершенных сборочных заданиях",
          link: "/reference/api/dbs/get-api-v3-dbs-orders",
        },
        {
          text: "Получить цены продавца и суммы к оплате",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-final-price",
        },
        {
          text: "Получить информацию о платной доставке",
          link: "/reference/api/dbs/post-api-v3-dbs-groups-info",
        },
        {
          text: "Информация о покупателе",
          link: "/reference/api/dbs/post-api-v3-dbs-orders-client",
        },
        {
          text: "Информация о покупателе B2B",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-b2b-info",
        },
        {
          text: "Получить дату и время доставки",
          link: "/reference/api/dbs/post-api-v3-dbs-orders-delivery-date",
        },
        {
          text: "Получить статусы сборочных заданий",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-info",
        },
        {
          text: "Отменить сборочные задания",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-cancel",
        },
        {
          text: "Перевести сборочные задания на сборку",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-confirm",
        },
        {
          text: "Получить стикеры для сборочных заданий с доставкой в ПВЗ",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-stickers",
        },
        {
          text: "Перевести сборочные задания в доставку",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-deliver",
        },
        {
          text: "Сообщить о получении заказов",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-receive",
        },
        {
          text: "Сообщить об отказе от заказов",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-reject",
        },
        {
          text: "Получить идентификаторы маркировки сборочных заданий",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-details",
        },
        {
          text: "Удалить идентификаторы маркировки сборочных заданий",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-delete",
        },
        {
          text: "Закрепить коды маркировки Честного знака за сборочными заданиями",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-sgtin",
        },
        {
          text: "Закрепить УИН за сборочными заданиями",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-uin",
        },
        {
          text: "Закрепить IMEI за сборочными заданиями",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-imei",
        },
        {
          text: "Закрепить GTIN за сборочными заданиями",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-gtin",
        },
        {
          text: "Закрепить номера ДТ за сборочными заданиями",
          link: "/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-customs-declaration",
        },
      ],
    },
    {
      text: "Самовывоз · in-store-pickup",
      collapsed: true,
      items: [
        {
          text: "Получить список новых сборочных заданий",
          link: "/reference/api/in-store-pickup/get-api-v3-click-collect-orders-new",
        },
        {
          text: "Получить информацию о завершённых сборочных заданиях",
          link: "/reference/api/in-store-pickup/get-api-v3-click-collect-orders",
        },
        {
          text: "Получить цены продавца и суммы к оплате",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-final-price",
        },
        {
          text: "Перевести сборочные задания на сборку",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-confirm",
        },
        {
          text: "Сообщить, что сборочные задания готовы к выдаче",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-prepare",
        },
        {
          text: "Информация о покупателе",
          link: "/reference/api/in-store-pickup/post-api-v3-click-collect-orders-client",
        },
        {
          text: "Проверить, что заказ принадлежит покупателю",
          link: "/reference/api/in-store-pickup/post-api-v3-click-collect-orders-client-identity",
        },
        {
          text: "Сообщить, что заказы приняты покупателями",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-receive",
        },
        {
          text: "Сообщить об отказе от заказов",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-reject",
        },
        {
          text: "Получить статусы сборочных заданий",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-info",
        },
        {
          text: "Отменить сборочные задания",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-cancel",
        },
        {
          text: "Получить идентификаторы маркировки сборочных заданий",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-details",
        },
        {
          text: "Удалить идентификаторы маркировки сборочных заданий",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-delete",
        },
        {
          text: "Закрепить коды маркировки Честного знака за сборочными заданиями",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-sgtin",
        },
        {
          text: "Закрепить УИН за сборочными заданиями",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-uin",
        },
        {
          text: "Закрепить IMEI за сборочными заданиями",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-imei",
        },
        {
          text: "Закрепить GTIN за сборочными заданиями",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-gtin",
        },
        {
          text: "Закрепить номера ДТ за сборочными заданиями",
          link: "/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-customs-declaration",
        },
      ],
    },
    {
      text: "Поставки FBW · orders-fbw",
      collapsed: true,
      items: [
        {
          text: "Опции приёмки",
          link: "/reference/api/orders-fbw/post-api-v1-acceptance-options",
        },
        {
          text: "Список складов",
          link: "/reference/api/orders-fbw/get-api-v1-warehouses",
        },
        {
          text: "Транзитные направления",
          link: "/reference/api/orders-fbw/get-api-v1-transit-tariffs",
        },
        {
          text: "Список поставок",
          link: "/reference/api/orders-fbw/post-api-v1-supplies",
        },
        {
          text: "Детали поставки",
          link: "/reference/api/orders-fbw/get-api-v1-supplies-id",
        },
        {
          text: "Товары поставки",
          link: "/reference/api/orders-fbw/get-api-v1-supplies-id-goods",
        },
        {
          text: "Упаковка поставки",
          link: "/reference/api/orders-fbw/get-api-v1-supplies-id-package",
        },
        {
          text: "Список черновиков",
          link: "/reference/api/orders-fbw/get-api-supplies-v1-drafts",
        },
        {
          text: "Создать черновик",
          link: "/reference/api/orders-fbw/post-api-supplies-v1-drafts",
        },
        {
          text: "Удалить черновик",
          link: "/reference/api/orders-fbw/delete-api-supplies-v1-drafts-draftid",
        },
        {
          text: "Список товаров в черновике",
          link: "/reference/api/orders-fbw/get-api-supplies-v1-drafts-draftid-items",
        },
        {
          text: "Добавить товары в черновик",
          link: "/reference/api/orders-fbw/post-api-supplies-v1-drafts-draftid-items",
        },
        {
          text: "Удалить товары из черновика",
          link: "/reference/api/orders-fbw/delete-api-supplies-v1-drafts-draftid-items",
        },
        {
          text: "Расхождения в поставке",
          link: "/reference/api/orders-fbw/get-api-supplies-v1-discrepancies-supplyid",
        },
      ],
    },
    {
      text: "Маркетинг и продвижение · promotion",
      collapsed: true,
      items: [
        {
          text: "Списки кампаний",
          link: "/reference/api/promotion/get-adv-v1-promotion-count",
        },
        {
          text: "Информация о кампаниях",
          link: "/reference/api/promotion/get-api-advert-v2-adverts",
        },
        {
          text: "Минимальные ставки для карточек товаров",
          link: "/reference/api/promotion/post-api-advert-v1-bids-min",
        },
        {
          text: "Создать кампанию",
          link: "/reference/api/promotion/post-adv-v2-seacat-save-ad",
        },
        {
          text: "Предметы для кампаний",
          link: "/reference/api/promotion/get-adv-v1-supplier-subjects",
        },
        {
          text: "Карточки товаров для кампаний",
          link: "/reference/api/promotion/post-adv-v2-supplier-nms",
        },
        {
          text: "Удаление кампании",
          link: "/reference/api/promotion/get-adv-v0-delete",
        },
        {
          text: "Переименование кампании",
          link: "/reference/api/promotion/post-adv-v0-rename",
        },
        {
          text: "Запуск кампании",
          link: "/reference/api/promotion/get-adv-v0-start",
        },
        {
          text: "Пауза кампании",
          link: "/reference/api/promotion/get-adv-v0-pause",
        },
        {
          text: "Завершение кампании",
          link: "/reference/api/promotion/get-adv-v0-stop",
        },
        {
          text: "Изменение мест размещения в кампаниях с ручной ставкой",
          link: "/reference/api/promotion/put-adv-v0-auction-placements",
        },
        {
          text: "Изменение ставок в кампаниях",
          link: "/reference/api/promotion/patch-api-advert-v1-bids",
        },
        {
          text: "Баланс",
          link: "/reference/api/promotion/get-adv-v1-balance",
        },
        {
          text: "Остатки бюджетов кампаний",
          link: "/reference/api/promotion/post-api-advert-v2-budget",
        },
        {
          text: "Бюджет кампании",
          link: "/reference/api/promotion/get-adv-v1-budget",
        },
        {
          text: "Пополнение бюджета кампании",
          link: "/reference/api/promotion/post-adv-v1-budget-deposit",
        },
        {
          text: "Получение истории затрат",
          link: "/reference/api/promotion/get-adv-v1-upd",
        },
        {
          text: "Получение истории пополнений счёта",
          link: "/reference/api/promotion/get-adv-v1-payments",
        },
        {
          text: "Изменение списка карточек товаров в кампаниях",
          link: "/reference/api/promotion/patch-adv-v0-auction-nms",
        },
        {
          text: "Рекомендуемые ставки для карточек товаров и поисковых кластеров",
          link: "/reference/api/promotion/get-api-advert-v0-bids-recommendations",
        },
        {
          text: "Статистика поисковых кластеров",
          link: "/reference/api/promotion/post-adv-v0-normquery-stats",
        },
        {
          text: "Список ставок поисковых кластеров",
          link: "/reference/api/promotion/post-adv-v0-normquery-get-bids",
        },
        {
          text: "Конфигурационные значения продвижения",
          link: "/reference/api/promotion/get-api-advert-v1-config",
        },
        {
          text: "Установить ставки для поисковых кластеров в валюте аккаунта продавца",
          link: "/reference/api/promotion/post-api-advert-v1-normquery-bids",
        },
        {
          text: "Установить ставки для поисковых кластеров",
          link: "/reference/api/promotion/post-adv-v0-normquery-bids",
        },
        {
          text: "Удалить ставки поисковых кластеров",
          link: "/reference/api/promotion/delete-adv-v0-normquery-bids",
        },
        {
          text: "Список минус-фраз кампаний",
          link: "/reference/api/promotion/post-adv-v0-normquery-get-minus",
        },
        {
          text: "Установка и удаление минус-фраз",
          link: "/reference/api/promotion/post-adv-v0-normquery-set-minus",
        },
        {
          text: "Количество медиакампаний",
          link: "/reference/api/promotion/get-adv-v1-count",
        },
        {
          text: "Список медиакампаний",
          link: "/reference/api/promotion/get-adv-v1-adverts",
        },
        {
          text: "Информация о медиакампании",
          link: "/reference/api/promotion/get-adv-v1-advert",
        },
        {
          text: "Статистика кампаний",
          link: "/reference/api/promotion/get-adv-v3-fullstats",
        },
        {
          text: "Статистика медиакампаний",
          link: "/reference/api/promotion/post-adv-v1-stats",
        },
        {
          text: "Список акций",
          link: "/reference/api/promotion/get-api-v1-calendar-promotions",
        },
        {
          text: "Детальная информация об акциях",
          link: "/reference/api/promotion/get-api-v1-calendar-promotions-details",
        },
        {
          text: "Список товаров для участия в акции",
          link: "/reference/api/promotion/get-api-v1-calendar-promotions-nomenclatures",
        },
        {
          text: "Добавить товар в акцию",
          link: "/reference/api/promotion/post-api-v1-calendar-promotions-upload",
        },
        {
          text: "Списки активных и неактивных поисковых кластеров",
          link: "/reference/api/promotion/post-adv-v0-normquery-list",
        },
        {
          text: "Статистика по поисковым кластерам с детализацией по дням",
          link: "/reference/api/promotion/post-adv-v1-normquery-stats",
        },
        {
          text: "Получить настройки дневных лимитов кампаний",
          link: "/reference/api/promotion/get-api-advert-v0-daily-limits",
        },
        {
          text: "Настройка дневных лимитов кампаний",
          link: "/reference/api/promotion/put-api-advert-v0-daily-limits",
        },
      ],
    },
    {
      text: "Общение с покупателями · communications",
      collapsed: true,
      items: [
        {
          text: "Непросмотренные отзывы и вопросы",
          link: "/reference/api/communications/get-api-v1-new-feedbacks-questions",
        },
        {
          text: "Неотвеченные вопросы",
          link: "/reference/api/communications/get-api-v1-questions-count-unanswered",
        },
        {
          text: "Количество вопросов",
          link: "/reference/api/communications/get-api-v1-questions-count",
        },
        {
          text: "Список вопросов",
          link: "/reference/api/communications/get-api-v1-questions",
        },
        {
          text: "Работа с вопросами",
          link: "/reference/api/communications/patch-api-v1-questions",
        },
        {
          text: "Получить вопрос по ID",
          link: "/reference/api/communications/get-api-v1-question",
        },
        {
          text: "Необработанные отзывы",
          link: "/reference/api/communications/get-api-v1-feedbacks-count-unanswered",
        },
        {
          text: "Количество отзывов",
          link: "/reference/api/communications/get-api-v1-feedbacks-count",
        },
        {
          text: "Список отзывов",
          link: "/reference/api/communications/get-api-v1-feedbacks",
        },
        {
          text: "Ответить на отзыв",
          link: "/reference/api/communications/post-api-v1-feedbacks-answer",
        },
        {
          text: "Отредактировать ответ на отзыв",
          link: "/reference/api/communications/patch-api-v1-feedbacks-answer",
        },
        {
          text: "Возврат товара по ID отзыва",
          link: "/reference/api/communications/post-api-v1-feedbacks-order-return",
        },
        {
          text: "Получить отзыв по ID",
          link: "/reference/api/communications/get-api-v1-feedback",
        },
        {
          text: "Список архивных отзывов",
          link: "/reference/api/communications/get-api-v1-feedbacks-archive",
        },
        {
          text: "Список закреплённых и откреплённых отзывов",
          link: "/reference/api/communications/get-api-feedbacks-v1-pins",
        },
        {
          text: "Закрепить отзывы",
          link: "/reference/api/communications/post-api-feedbacks-v1-pins",
        },
        {
          text: "Открепить отзывы",
          link: "/reference/api/communications/delete-api-feedbacks-v1-pins",
        },
        {
          text: "Количество закреплённых и откреплённых отзывов",
          link: "/reference/api/communications/get-api-feedbacks-v1-pins-count",
        },
        {
          text: "Лимиты закреплённых отзывов",
          link: "/reference/api/communications/get-api-feedbacks-v1-pins-limits",
        },
        {
          text: "Список чатов",
          link: "/reference/api/communications/get-api-v1-seller-chats",
        },
        {
          text: "События чатов",
          link: "/reference/api/communications/get-api-v1-seller-events",
        },
        {
          text: "Отправить сообщение",
          link: "/reference/api/communications/post-api-v1-seller-message",
        },
        {
          text: "Получить файл из сообщения",
          link: "/reference/api/communications/get-api-v1-seller-download-id",
        },
        {
          text: "Заявки покупателей на возврат",
          link: "/reference/api/communications/get-api-v1-claims",
        },
        {
          text: "Ответ на заявку покупателя",
          link: "/reference/api/communications/patch-api-v1-claim",
        },
      ],
    },
    {
      text: "Тарифы · rates",
      collapsed: true,
      items: [
        {
          text: "Комиссия по категориям товаров",
          link: "/reference/api/rates/get-api-v1-tariffs-commission",
        },
        {
          text: "Тарифы на поставку",
          link: "/reference/api/rates/get-api-tariffs-v1-acceptance-coefficients",
        },
        {
          text: "Тарифы для коробов",
          link: "/reference/api/rates/get-api-v1-tariffs-box",
        },
        {
          text: "Тарифы для монопаллет",
          link: "/reference/api/rates/get-api-v1-tariffs-pallet",
        },
        {
          text: "Тарифы на возврат",
          link: "/reference/api/rates/get-api-v1-tariffs-return",
        },
      ],
    },
    {
      text: "Аналитика и данные · analytics",
      collapsed: true,
      items: [
        {
          text: "Статистика карточек товаров за период",
          link: "/reference/api/analytics/post-api-analytics-v3-sales-funnel-products",
        },
        {
          text: "Статистика карточек товаров по дням",
          link: "/reference/api/analytics/post-api-analytics-v3-sales-funnel-products-history",
        },
        {
          text: "Статистика групп карточек товаров по дням",
          link: "/reference/api/analytics/post-api-analytics-v3-sales-funnel-grouped-history",
        },
        {
          text: "Создать отчёт",
          link: "/reference/api/analytics/post-api-v2-nm-report-downloads",
        },
        {
          text: "Получить список отчётов",
          link: "/reference/api/analytics/get-api-v2-nm-report-downloads",
        },
        {
          text: "Сгенерировать отчёт повторно",
          link: "/reference/api/analytics/post-api-v2-nm-report-downloads-retry",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/analytics/get-api-v2-nm-report-downloads-file-downloadid",
        },
        {
          text: "Основная страница",
          link: "/reference/api/analytics/post-api-v2-search-report-report",
        },
        {
          text: "Пагинация по группам",
          link: "/reference/api/analytics/post-api-v2-search-report-table-groups",
        },
        {
          text: "Пагинация по товарам в группе",
          link: "/reference/api/analytics/post-api-v2-search-report-table-details",
        },
        {
          text: "Поисковые запросы по товару",
          link: "/reference/api/analytics/post-api-v2-search-report-product-search-texts",
        },
        {
          text: "Заказы и позиции по поисковым запросам товара",
          link: "/reference/api/analytics/post-api-v2-search-report-product-orders",
        },
        {
          text: "Остатки на складах WB",
          link: "/reference/api/analytics/post-api-analytics-v1-stocks-report-wb-warehouses",
        },
        {
          text: "Остатки на складах продавца",
          link: "/reference/api/analytics/post-api-analytics-v1-stocks-report-seller-warehouses",
        },
        {
          text: "Данные по группам",
          link: "/reference/api/analytics/post-api-v2-stocks-report-products-groups",
        },
        {
          text: "Данные по товарам",
          link: "/reference/api/analytics/post-api-v2-stocks-report-products-products",
        },
        {
          text: "Данные по размерам",
          link: "/reference/api/analytics/post-api-v2-stocks-report-products-sizes",
        },
        {
          text: "Данные по складам",
          link: "/reference/api/analytics/post-api-v2-stocks-report-offices",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/analytics/post-api-analytics-v2-item-rating",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/analytics/post-api-analytics-v1-order-feed",
        },
      ],
    },
    {
      text: "Отчёты · reports",
      collapsed: true,
      items: [
        {
          text: "Заказы",
          link: "/reference/api/reports/get-api-v1-supplier-orders",
        },
        {
          text: "Продажи",
          link: "/reference/api/reports/get-api-v1-supplier-sales",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/reports/post-api-v1-analytics-excise-report",
        },
        {
          text: "Создать отчёт",
          link: "/reference/api/reports/get-api-v1-warehouse-remains",
        },
        {
          text: "Проверить статус",
          link: "/reference/api/reports/get-api-v1-warehouse-remains-tasks-task-id-status",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/reports/get-api-v1-warehouse-remains-tasks-task-id-download",
        },
        {
          text: "Удержания за занижение габаритов упаковки",
          link: "/reference/api/reports/get-api-analytics-v1-measurement-penalties",
        },
        {
          text: "Замеры склада",
          link: "/reference/api/reports/get-api-analytics-v1-warehouse-measurements",
        },
        {
          text: "Подмены и неверные вложения",
          link: "/reference/api/reports/get-api-analytics-v1-deductions",
        },
        {
          text: "Самовыкупы",
          link: "/reference/api/reports/get-api-v1-analytics-antifraud-details",
        },
        {
          text: "Маркировка товара",
          link: "/reference/api/reports/get-api-v1-analytics-goods-labeling",
        },
        {
          text: "Создать отчёт",
          link: "/reference/api/reports/get-api-v1-acceptance-report",
        },
        {
          text: "Проверить статус",
          link: "/reference/api/reports/get-api-v1-acceptance-report-tasks-task-id-status",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/reports/get-api-v1-acceptance-report-tasks-task-id-download",
        },
        {
          text: "Создать отчёт",
          link: "/reference/api/reports/get-api-v1-paid-storage",
        },
        {
          text: "Проверить статус",
          link: "/reference/api/reports/get-api-v1-paid-storage-tasks-task-id-status",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/reports/get-api-v1-paid-storage-tasks-task-id-download",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/reports/get-api-v1-analytics-region-sale",
        },
        {
          text: "Бренды продавца",
          link: "/reference/api/reports/get-api-v1-analytics-brand-share-brands",
        },
        {
          text: "Родительские категории бренда",
          link: "/reference/api/reports/get-api-v1-analytics-brand-share-parent-subjects",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/reports/get-api-v1-analytics-brand-share",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/reports/get-api-v1-analytics-banned-products-blocked",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/reports/get-api-v1-analytics-goods-return",
        },
        {
          text: "Получить отчёт",
          link: "/reference/api/reports/get-api-analytics-v1-item-returns",
        },
      ],
    },
    {
      text: "Документы и бухгалтерия · finances",
      collapsed: true,
      items: [
        {
          text: "Получить баланс продавца",
          link: "/reference/api/finances/get-api-v1-account-balance",
        },
        {
          text: "Список отчётов реализации",
          link: "/reference/api/finances/post-api-finance-v1-sales-reports-list",
        },
        {
          text: "Детализации к отчётам реализации по ID отчётов",
          link: "/reference/api/finances/post-api-finance-v1-sales-reports-detailed-reportid",
        },
        {
          text: "Детализации к отчётам реализации за период",
          link: "/reference/api/finances/post-api-finance-v1-sales-reports-detailed",
        },
        {
          text: "Список отчётов об издержках на приём платежей",
          link: "/reference/api/finances/post-api-finance-v1-acquiring-list",
        },
        {
          text: "Детализации к отчётам об издержках на приём платежей по ID отчётов",
          link: "/reference/api/finances/post-api-finance-v1-acquiring-detailed-reportid",
        },
        {
          text: "Детализации к отчётам об издержках на приём платежей за период",
          link: "/reference/api/finances/post-api-finance-v1-acquiring-detailed",
        },
        {
          text: "Категории документов",
          link: "/reference/api/finances/get-api-v1-documents-categories",
        },
        {
          text: "Список документов",
          link: "/reference/api/finances/get-api-v1-documents-list",
        },
        {
          text: "Получить документ",
          link: "/reference/api/finances/get-api-v1-documents-download",
        },
        {
          text: "Получить документы",
          link: "/reference/api/finances/post-api-v1-documents-download-all",
        },
      ],
    },
  ],
  en: [
    {
      text: "API reference",
      link: "/en/reference/api/",
    },
    {
      text: "Общее · general",
      collapsed: true,
      items: [
        {
          text: "Проверка подключения",
          link: "/en/reference/api/general/get-ping",
        },
        {
          text: "Получение новостей портала продавцов",
          link: "/en/reference/api/general/get-api-communications-v2-news",
        },
        {
          text: "Получить информацию о продавце",
          link: "/en/reference/api/general/get-api-v1-seller-info",
        },
        {
          text: "Получить рейтинг продавца",
          link: "/en/reference/api/general/get-api-common-v1-rating",
        },
        {
          text: "Получить информацию о подписке Джем",
          link: "/en/reference/api/general/get-api-common-v1-subscriptions",
        },
        {
          text: "Получить информацию об опциях Конструктора тарифов",
          link: "/en/reference/api/general/get-api-common-v1-tariff-constructor-options",
        },
        {
          text: "Создать приглашение для нового пользователя",
          link: "/en/reference/api/general/post-api-v1-invite",
        },
        {
          text: "Получить список активных или приглашённых пользователей продавца",
          link: "/en/reference/api/general/get-api-v1-users",
        },
        {
          text: "Изменить права доступа пользователей",
          link: "/en/reference/api/general/put-api-v1-users-access",
        },
        {
          text: "Удалить пользователя",
          link: "/en/reference/api/general/delete-api-v1-user",
        },
      ],
    },
    {
      text: "Работа с товарами · items",
      collapsed: true,
      items: [
        {
          text: "Родительские категории товаров",
          link: "/en/reference/api/items/get-content-v2-object-parent-all",
        },
        {
          text: "Список предметов",
          link: "/en/reference/api/items/get-content-v2-object-all",
        },
        {
          text: "Характеристики предмета",
          link: "/en/reference/api/items/get-content-v2-object-charcs-subjectid",
        },
        {
          text: "Цвет",
          link: "/en/reference/api/items/get-content-v2-directory-colors",
        },
        {
          text: "Пол",
          link: "/en/reference/api/items/get-content-v2-directory-kinds",
        },
        {
          text: "Страна производства",
          link: "/en/reference/api/items/get-content-v2-directory-countries",
        },
        {
          text: "Сезон",
          link: "/en/reference/api/items/get-content-v2-directory-seasons",
        },
        {
          text: "Ставка НДС",
          link: "/en/reference/api/items/get-content-v2-directory-vat",
        },
        {
          text: "Код ТН ВЭД предмета",
          link: "/en/reference/api/items/get-content-v2-directory-tnved",
        },
        {
          text: "Список кодов ТН ВЭД",
          link: "/en/reference/api/items/get-api-content-v2-directory-tnved-all",
        },
        {
          text: "Код ОКПД2 предмета",
          link: "/en/reference/api/items/get-api-content-v2-directory-okpd",
        },
        {
          text: "Список кодов ОКПД2",
          link: "/en/reference/api/items/get-api-content-v2-directory-okpd-all",
        },
        {
          text: "Бренды",
          link: "/en/reference/api/items/get-api-content-v1-brands",
        },
        {
          text: "Список ярлыков",
          link: "/en/reference/api/items/get-content-v2-tags",
        },
        {
          text: "Создание ярлыка",
          link: "/en/reference/api/items/post-content-v2-tag",
        },
        {
          text: "Изменение ярлыка",
          link: "/en/reference/api/items/patch-content-v2-tag-id",
        },
        {
          text: "Удаление ярлыка",
          link: "/en/reference/api/items/delete-content-v2-tag-id",
        },
        {
          text: "Управление ярлыками в карточке товара",
          link: "/en/reference/api/items/post-content-v2-tag-nomenclature-link",
        },
        {
          text: "Список карточек товаров",
          link: "/en/reference/api/items/post-content-v2-get-cards-list",
        },
        {
          text: "Список несозданных карточек товаров с ошибками",
          link: "/en/reference/api/items/post-content-v2-cards-error-list",
        },
        {
          text: "Редактирование карточек товаров",
          link: "/en/reference/api/items/post-content-v2-cards-update",
        },
        {
          text: "Объединение и разъединение карточек товаров",
          link: "/en/reference/api/items/post-content-v2-cards-movenm",
        },
        {
          text: "Перенос карточек товаров в корзину",
          link: "/en/reference/api/items/post-content-v2-cards-delete-trash",
        },
        {
          text: "Восстановление карточек товаров из корзины",
          link: "/en/reference/api/items/post-content-v2-cards-recover",
        },
        {
          text: "Список карточек товаров в корзине",
          link: "/en/reference/api/items/post-content-v2-get-cards-trash",
        },
        {
          text: "Лимиты карточек товаров",
          link: "/en/reference/api/items/get-content-v2-cards-limits",
        },
        {
          text: "Генерация баркодов",
          link: "/en/reference/api/items/post-content-v2-barcodes",
        },
        {
          text: "Создание карточек товаров",
          link: "/en/reference/api/items/post-content-v2-cards-upload",
        },
        {
          text: "Создание карточек товаров с присоединением",
          link: "/en/reference/api/items/post-content-v2-cards-upload-add",
        },
        {
          text: "Загрузить медиафайл",
          link: "/en/reference/api/items/post-content-v3-media-file",
        },
        {
          text: "Загрузить медиафайлы по ссылкам",
          link: "/en/reference/api/items/post-content-v3-media-save",
        },
        {
          text: "Список рекомендаций в карточках товаров",
          link: "/en/reference/api/items/post-api-content-v1-recommendations-list",
        },
        {
          text: "Установить рекомендации для товаров",
          link: "/en/reference/api/items/post-api-content-v1-recommendations-set",
        },
        {
          text: "Установить цены и скидки",
          link: "/en/reference/api/items/post-api-v2-upload-task",
        },
        {
          text: "Установить цены для размеров",
          link: "/en/reference/api/items/post-api-v2-upload-task-size",
        },
        {
          text: "Установить скидки WB Клуба",
          link: "/en/reference/api/items/post-api-v2-upload-task-club-discount",
        },
        {
          text: "Установить оптовые скидки для B2B-продаж",
          link: "/en/reference/api/items/post-api-discounts-prices-v1-upload-task-b2b-wholesale",
        },
        {
          text: "Состояние обработанной загрузки",
          link: "/en/reference/api/items/get-api-v2-history-tasks",
        },
        {
          text: "Детализация обработанной загрузки",
          link: "/en/reference/api/items/get-api-v2-history-goods-task",
        },
        {
          text: "Состояние необработанной загрузки",
          link: "/en/reference/api/items/get-api-v2-buffer-tasks",
        },
        {
          text: "Детализация необработанной загрузки",
          link: "/en/reference/api/items/get-api-v2-buffer-goods-task",
        },
        {
          text: "Получить товары с ценами",
          link: "/en/reference/api/items/get-api-v2-list-goods-filter",
        },
        {
          text: "Получить товары с ценами по артикулам",
          link: "/en/reference/api/items/post-api-v2-list-goods-filter",
        },
        {
          text: "Получить размеры товара с ценами",
          link: "/en/reference/api/items/get-api-v2-list-goods-size-nm",
        },
        {
          text: "Получить товары в карантине",
          link: "/en/reference/api/items/get-api-v2-quarantine-goods",
        },
        {
          text: "Обновить остатки товаров",
          link: "/en/reference/api/items/put-api-v3-stocks-warehouseid",
        },
        {
          text: "Удалить остатки товаров",
          link: "/en/reference/api/items/delete-api-v3-stocks-warehouseid",
        },
        {
          text: "Получить остатки товаров",
          link: "/en/reference/api/items/post-api-v3-stocks-warehouseid",
        },
        {
          text: "Получить список складов WB",
          link: "/en/reference/api/items/get-api-v3-offices",
        },
        {
          text: "Получить список складов продавца",
          link: "/en/reference/api/items/get-api-v3-warehouses",
        },
        {
          text: "Создать склад продавца",
          link: "/en/reference/api/items/post-api-v3-warehouses",
        },
        {
          text: "Обновить склад продавца",
          link: "/en/reference/api/items/put-api-v3-warehouses-warehouseid",
        },
        {
          text: "Удалить склад продавца",
          link: "/en/reference/api/items/delete-api-v3-warehouses-warehouseid",
        },
        {
          text: "Список контактов",
          link: "/en/reference/api/items/get-api-v3-dbw-warehouses-warehouseid-contacts",
        },
        {
          text: "Обновить список контактов",
          link: "/en/reference/api/items/put-api-v3-dbw-warehouses-warehouseid-contacts",
        },
      ],
    },
    {
      text: "Заказы FBS · orders-fbs",
      collapsed: true,
      items: [
        {
          text: "Получить список складов, для которых требуется пропуск",
          link: "/en/reference/api/orders-fbs/get-api-v3-passes-offices",
        },
        {
          text: "Получить список пропусков",
          link: "/en/reference/api/orders-fbs/get-api-v3-passes",
        },
        {
          text: "Создать пропуск",
          link: "/en/reference/api/orders-fbs/post-api-v3-passes",
        },
        {
          text: "Обновить пропуск",
          link: "/en/reference/api/orders-fbs/put-api-v3-passes-passid",
        },
        {
          text: "Удалить пропуск",
          link: "/en/reference/api/orders-fbs/delete-api-v3-passes-passid",
        },
        {
          text: "Получить список новых сборочных заданий",
          link: "/en/reference/api/orders-fbs/get-api-v3-orders-new",
        },
        {
          text: "Получить информацию о сборочных заданиях",
          link: "/en/reference/api/orders-fbs/get-api-v3-orders",
        },
        {
          text: "Получить статусы сборочных заданий",
          link: "/en/reference/api/orders-fbs/post-api-v3-orders-status",
        },
        {
          text: "Получить все сборочные задания для повторной отгрузки",
          link: "/en/reference/api/orders-fbs/get-api-v3-supplies-orders-reshipment",
        },
        {
          text: "Отменить сборочное задание",
          link: "/en/reference/api/orders-fbs/patch-api-v3-orders-orderid-cancel",
        },
        {
          text: "Получить стикеры сборочных заданий",
          link: "/en/reference/api/orders-fbs/post-api-v3-orders-stickers",
        },
        {
          text: "Получить стикеры сборочных заданий трансграничных поставок",
          link: "/en/reference/api/orders-fbs/post-api-v3-orders-stickers-cross-border",
        },
        {
          text: "История статусов для сборочных заданий трансграничных поставок",
          link: "/en/reference/api/orders-fbs/post-api-v3-orders-status-history",
        },
        {
          text: "Заказы с информацией по клиенту",
          link: "/en/reference/api/orders-fbs/post-api-v3-orders-client",
        },
        {
          text: "Получить список архивных сборочных заданий",
          link: "/en/reference/api/orders-fbs/get-api-marketplace-v3-fbs-orders-archive",
        },
        {
          text: "Получить идентификаторы маркировки сборочных заданий",
          link: "/en/reference/api/orders-fbs/post-api-marketplace-v3-orders-meta",
        },
        {
          text: "Удалить идентификаторы маркировки сборочного задания",
          link: "/en/reference/api/orders-fbs/delete-api-v3-orders-orderid-meta",
        },
        {
          text: "Закрепить код маркировки Честного знака за сборочным заданием",
          link: "/en/reference/api/orders-fbs/put-api-v3-orders-orderid-meta-sgtin",
        },
        {
          text: "Закрепить УИН за сборочным заданием",
          link: "/en/reference/api/orders-fbs/put-api-v3-orders-orderid-meta-uin",
        },
        {
          text: "Закрепить IMEI за сборочным заданием",
          link: "/en/reference/api/orders-fbs/put-api-v3-orders-orderid-meta-imei",
        },
        {
          text: "Закрепить GTIN за сборочным заданием",
          link: "/en/reference/api/orders-fbs/put-api-v3-orders-orderid-meta-gtin",
        },
        {
          text: "Закрепить за сборочным заданием срок годности товара",
          link: "/en/reference/api/orders-fbs/put-api-v3-orders-orderid-meta-expiration",
        },
        {
          text: "Закрепить номер ДТ за сборочным заданием",
          link: "/en/reference/api/orders-fbs/put-api-marketplace-v3-orders-orderid-meta-customs-declaration",
        },
        {
          text: "Создать новую поставку",
          link: "/en/reference/api/orders-fbs/post-api-v3-supplies",
        },
        {
          text: "Получить список поставок",
          link: "/en/reference/api/orders-fbs/get-api-v3-supplies",
        },
        {
          text: "Добавить сборочные задания к поставке",
          link: "/en/reference/api/orders-fbs/patch-api-marketplace-v3-supplies-supplyid-orders",
        },
        {
          text: "Получить информацию о поставке",
          link: "/en/reference/api/orders-fbs/get-api-v3-supplies-supplyid",
        },
        {
          text: "Удалить поставку",
          link: "/en/reference/api/orders-fbs/delete-api-v3-supplies-supplyid",
        },
        {
          text: "Получить ID сборочных заданий поставки",
          link: "/en/reference/api/orders-fbs/get-api-marketplace-v3-supplies-supplyid-order-ids",
        },
        {
          text: "Получить список пунктов отгрузки поставок",
          link: "/en/reference/api/orders-fbs/get-api-marketplace-v3-fbs-shipping-points",
        },
        {
          text: "Установить параметры отгрузки поставок",
          link: "/en/reference/api/orders-fbs/patch-api-marketplace-v3-fbs-supplies-shipping-method",
        },
        {
          text: "Установить ID ЭТрН поставок",
          link: "/en/reference/api/orders-fbs/patch-api-marketplace-v3-fbs-supplies-waybill",
        },
        {
          text: "Передать поставку в доставку",
          link: "/en/reference/api/orders-fbs/patch-api-v3-supplies-supplyid-deliver",
        },
        {
          text: "Получить QR-код поставки",
          link: "/en/reference/api/orders-fbs/get-api-v3-supplies-supplyid-barcode",
        },
        {
          text: "Получить список грузомест поставки",
          link: "/en/reference/api/orders-fbs/get-api-v3-supplies-supplyid-trbx",
        },
        {
          text: "Добавить грузоместа к поставке",
          link: "/en/reference/api/orders-fbs/post-api-v3-supplies-supplyid-trbx",
        },
        {
          text: "Удалить грузоместа из поставки",
          link: "/en/reference/api/orders-fbs/delete-api-v3-supplies-supplyid-trbx",
        },
        {
          text: "Получить стикеры грузомест поставки",
          link: "/en/reference/api/orders-fbs/post-api-v3-supplies-supplyid-trbx-stickers",
        },
        {
          text: "Получить список стран ОКСМ",
          link: "/en/reference/api/orders-fbs/get-api-marketplace-v3-fbs-dictionaries-countries-oksm",
        },
        {
          text: "Добавить данные СПОТ в поставку",
          link: "/en/reference/api/orders-fbs/put-api-marketplace-v3-fbs-supplies-supplyid-spot",
        },
        {
          text: "Получить данные СПОТ для списка поставок",
          link: "/en/reference/api/orders-fbs/post-api-marketplace-v3-fbs-supplies-spot-list",
        },
        {
          text: "Получить QR-код СПОТ",
          link: "/en/reference/api/orders-fbs/get-api-marketplace-v3-fbs-supplies-supplyid-stickers-spot",
        },
        {
          text: "Получить настройки автовозврата продавца",
          link: "/en/reference/api/orders-fbs/get-api-marketplace-v3-fbs-settings-autoreturns",
        },
        {
          text: "Обновить настройки автовозврата продавца",
          link: "/en/reference/api/orders-fbs/patch-api-marketplace-v3-fbs-settings-autoreturns",
        },
        {
          text: "Получить настройки автовозврата товаров",
          link: "/en/reference/api/orders-fbs/post-api-marketplace-v3-fbs-settings-autoreturns-items",
        },
        {
          text: "Обновить настройки автовозврата товаров",
          link: "/en/reference/api/orders-fbs/patch-api-marketplace-v3-fbs-settings-autoreturns-items",
        },
        {
          text: "Получить предметы, которые не хранятся на складах WB",
          link: "/en/reference/api/orders-fbs/get-api-marketplace-v3-fbs-settings-autoreturns-subcategories-restricted",
        },
      ],
    },
    {
      text: "Заказы DBW · orders-dbw",
      collapsed: true,
      items: [
        {
          text: "Получить список новых сборочных заданий",
          link: "/en/reference/api/orders-dbw/get-api-v3-dbw-orders-new",
        },
        {
          text: "Получить информацию о завершенных сборочных заданиях",
          link: "/en/reference/api/orders-dbw/get-api-v3-dbw-orders",
        },
        {
          text: "Получить дату и время доставки",
          link: "/en/reference/api/orders-dbw/post-api-v3-dbw-orders-delivery-date",
        },
        {
          text: "Информация о покупателе",
          link: "/en/reference/api/orders-dbw/post-api-marketplace-v3-dbw-orders-client",
        },
        {
          text: "Получить статусы сборочных заданий",
          link: "/en/reference/api/orders-dbw/post-api-v3-dbw-orders-status",
        },
        {
          text: "Перевести на сборку",
          link: "/en/reference/api/orders-dbw/patch-api-v3-dbw-orders-orderid-confirm",
        },
        {
          text: "Получить стикеры сборочных заданий",
          link: "/en/reference/api/orders-dbw/post-api-v3-dbw-orders-stickers",
        },
        {
          text: "Перевести сборочные задания в доставку",
          link: "/en/reference/api/orders-dbw/post-api-marketplace-v3-dbw-orders-status-deliver",
        },
        {
          text: "Информация о курьере",
          link: "/en/reference/api/orders-dbw/post-api-v3-dbw-orders-courier",
        },
        {
          text: "Отменить сборочное задание",
          link: "/en/reference/api/orders-dbw/patch-api-v3-dbw-orders-orderid-cancel",
        },
        {
          text: "Получить идентификаторы маркировки сборочных заданий",
          link: "/en/reference/api/orders-dbw/post-api-marketplace-v3-dbw-orders-meta-details",
        },
        {
          text: "Удалить идентификаторы маркировки сборочных заданий",
          link: "/en/reference/api/orders-dbw/post-api-marketplace-v3-dbw-orders-meta-delete",
        },
        {
          text: "Закрепить коды маркировки Честного знака за сборочными заданиями",
          link: "/en/reference/api/orders-dbw/post-api-marketplace-v3-dbw-orders-meta-sgtin",
        },
        {
          text: "Закрепить УИН за сборочным заданием",
          link: "/en/reference/api/orders-dbw/put-api-v3-dbw-orders-orderid-meta-uin",
        },
        {
          text: "Закрепить IMEI за сборочным заданием",
          link: "/en/reference/api/orders-dbw/put-api-v3-dbw-orders-orderid-meta-imei",
        },
        {
          text: "Закрепить GTIN за сборочным заданием",
          link: "/en/reference/api/orders-dbw/put-api-v3-dbw-orders-orderid-meta-gtin",
        },
      ],
    },
    {
      text: "DBS · dbs",
      collapsed: true,
      items: [
        {
          text: "Получить список новых сборочных заданий",
          link: "/en/reference/api/dbs/get-api-v3-dbs-orders-new",
        },
        {
          text: "Получить информацию о завершенных сборочных заданиях",
          link: "/en/reference/api/dbs/get-api-v3-dbs-orders",
        },
        {
          text: "Получить цены продавца и суммы к оплате",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-final-price",
        },
        {
          text: "Получить информацию о платной доставке",
          link: "/en/reference/api/dbs/post-api-v3-dbs-groups-info",
        },
        {
          text: "Информация о покупателе",
          link: "/en/reference/api/dbs/post-api-v3-dbs-orders-client",
        },
        {
          text: "Информация о покупателе B2B",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-b2b-info",
        },
        {
          text: "Получить дату и время доставки",
          link: "/en/reference/api/dbs/post-api-v3-dbs-orders-delivery-date",
        },
        {
          text: "Получить статусы сборочных заданий",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-info",
        },
        {
          text: "Отменить сборочные задания",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-cancel",
        },
        {
          text: "Перевести сборочные задания на сборку",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-confirm",
        },
        {
          text: "Получить стикеры для сборочных заданий с доставкой в ПВЗ",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-stickers",
        },
        {
          text: "Перевести сборочные задания в доставку",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-deliver",
        },
        {
          text: "Сообщить о получении заказов",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-receive",
        },
        {
          text: "Сообщить об отказе от заказов",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-status-reject",
        },
        {
          text: "Получить идентификаторы маркировки сборочных заданий",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-details",
        },
        {
          text: "Удалить идентификаторы маркировки сборочных заданий",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-delete",
        },
        {
          text: "Закрепить коды маркировки Честного знака за сборочными заданиями",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-sgtin",
        },
        {
          text: "Закрепить УИН за сборочными заданиями",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-uin",
        },
        {
          text: "Закрепить IMEI за сборочными заданиями",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-imei",
        },
        {
          text: "Закрепить GTIN за сборочными заданиями",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-gtin",
        },
        {
          text: "Закрепить номера ДТ за сборочными заданиями",
          link: "/en/reference/api/dbs/post-api-marketplace-v3-dbs-orders-meta-customs-declaration",
        },
      ],
    },
    {
      text: "Самовывоз · in-store-pickup",
      collapsed: true,
      items: [
        {
          text: "Получить список новых сборочных заданий",
          link: "/en/reference/api/in-store-pickup/get-api-v3-click-collect-orders-new",
        },
        {
          text: "Получить информацию о завершённых сборочных заданиях",
          link: "/en/reference/api/in-store-pickup/get-api-v3-click-collect-orders",
        },
        {
          text: "Получить цены продавца и суммы к оплате",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-final-price",
        },
        {
          text: "Перевести сборочные задания на сборку",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-confirm",
        },
        {
          text: "Сообщить, что сборочные задания готовы к выдаче",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-prepare",
        },
        {
          text: "Информация о покупателе",
          link: "/en/reference/api/in-store-pickup/post-api-v3-click-collect-orders-client",
        },
        {
          text: "Проверить, что заказ принадлежит покупателю",
          link: "/en/reference/api/in-store-pickup/post-api-v3-click-collect-orders-client-identity",
        },
        {
          text: "Сообщить, что заказы приняты покупателями",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-receive",
        },
        {
          text: "Сообщить об отказе от заказов",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-reject",
        },
        {
          text: "Получить статусы сборочных заданий",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-info",
        },
        {
          text: "Отменить сборочные задания",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-status-cancel",
        },
        {
          text: "Получить идентификаторы маркировки сборочных заданий",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-details",
        },
        {
          text: "Удалить идентификаторы маркировки сборочных заданий",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-delete",
        },
        {
          text: "Закрепить коды маркировки Честного знака за сборочными заданиями",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-sgtin",
        },
        {
          text: "Закрепить УИН за сборочными заданиями",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-uin",
        },
        {
          text: "Закрепить IMEI за сборочными заданиями",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-imei",
        },
        {
          text: "Закрепить GTIN за сборочными заданиями",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-gtin",
        },
        {
          text: "Закрепить номера ДТ за сборочными заданиями",
          link: "/en/reference/api/in-store-pickup/post-api-marketplace-v3-click-collect-orders-meta-customs-declaration",
        },
      ],
    },
    {
      text: "Поставки FBW · orders-fbw",
      collapsed: true,
      items: [
        {
          text: "Опции приёмки",
          link: "/en/reference/api/orders-fbw/post-api-v1-acceptance-options",
        },
        {
          text: "Список складов",
          link: "/en/reference/api/orders-fbw/get-api-v1-warehouses",
        },
        {
          text: "Транзитные направления",
          link: "/en/reference/api/orders-fbw/get-api-v1-transit-tariffs",
        },
        {
          text: "Список поставок",
          link: "/en/reference/api/orders-fbw/post-api-v1-supplies",
        },
        {
          text: "Детали поставки",
          link: "/en/reference/api/orders-fbw/get-api-v1-supplies-id",
        },
        {
          text: "Товары поставки",
          link: "/en/reference/api/orders-fbw/get-api-v1-supplies-id-goods",
        },
        {
          text: "Упаковка поставки",
          link: "/en/reference/api/orders-fbw/get-api-v1-supplies-id-package",
        },
        {
          text: "Список черновиков",
          link: "/en/reference/api/orders-fbw/get-api-supplies-v1-drafts",
        },
        {
          text: "Создать черновик",
          link: "/en/reference/api/orders-fbw/post-api-supplies-v1-drafts",
        },
        {
          text: "Удалить черновик",
          link: "/en/reference/api/orders-fbw/delete-api-supplies-v1-drafts-draftid",
        },
        {
          text: "Список товаров в черновике",
          link: "/en/reference/api/orders-fbw/get-api-supplies-v1-drafts-draftid-items",
        },
        {
          text: "Добавить товары в черновик",
          link: "/en/reference/api/orders-fbw/post-api-supplies-v1-drafts-draftid-items",
        },
        {
          text: "Удалить товары из черновика",
          link: "/en/reference/api/orders-fbw/delete-api-supplies-v1-drafts-draftid-items",
        },
        {
          text: "Расхождения в поставке",
          link: "/en/reference/api/orders-fbw/get-api-supplies-v1-discrepancies-supplyid",
        },
      ],
    },
    {
      text: "Маркетинг и продвижение · promotion",
      collapsed: true,
      items: [
        {
          text: "Списки кампаний",
          link: "/en/reference/api/promotion/get-adv-v1-promotion-count",
        },
        {
          text: "Информация о кампаниях",
          link: "/en/reference/api/promotion/get-api-advert-v2-adverts",
        },
        {
          text: "Минимальные ставки для карточек товаров",
          link: "/en/reference/api/promotion/post-api-advert-v1-bids-min",
        },
        {
          text: "Создать кампанию",
          link: "/en/reference/api/promotion/post-adv-v2-seacat-save-ad",
        },
        {
          text: "Предметы для кампаний",
          link: "/en/reference/api/promotion/get-adv-v1-supplier-subjects",
        },
        {
          text: "Карточки товаров для кампаний",
          link: "/en/reference/api/promotion/post-adv-v2-supplier-nms",
        },
        {
          text: "Удаление кампании",
          link: "/en/reference/api/promotion/get-adv-v0-delete",
        },
        {
          text: "Переименование кампании",
          link: "/en/reference/api/promotion/post-adv-v0-rename",
        },
        {
          text: "Запуск кампании",
          link: "/en/reference/api/promotion/get-adv-v0-start",
        },
        {
          text: "Пауза кампании",
          link: "/en/reference/api/promotion/get-adv-v0-pause",
        },
        {
          text: "Завершение кампании",
          link: "/en/reference/api/promotion/get-adv-v0-stop",
        },
        {
          text: "Изменение мест размещения в кампаниях с ручной ставкой",
          link: "/en/reference/api/promotion/put-adv-v0-auction-placements",
        },
        {
          text: "Изменение ставок в кампаниях",
          link: "/en/reference/api/promotion/patch-api-advert-v1-bids",
        },
        {
          text: "Баланс",
          link: "/en/reference/api/promotion/get-adv-v1-balance",
        },
        {
          text: "Остатки бюджетов кампаний",
          link: "/en/reference/api/promotion/post-api-advert-v2-budget",
        },
        {
          text: "Бюджет кампании",
          link: "/en/reference/api/promotion/get-adv-v1-budget",
        },
        {
          text: "Пополнение бюджета кампании",
          link: "/en/reference/api/promotion/post-adv-v1-budget-deposit",
        },
        {
          text: "Получение истории затрат",
          link: "/en/reference/api/promotion/get-adv-v1-upd",
        },
        {
          text: "Получение истории пополнений счёта",
          link: "/en/reference/api/promotion/get-adv-v1-payments",
        },
        {
          text: "Изменение списка карточек товаров в кампаниях",
          link: "/en/reference/api/promotion/patch-adv-v0-auction-nms",
        },
        {
          text: "Рекомендуемые ставки для карточек товаров и поисковых кластеров",
          link: "/en/reference/api/promotion/get-api-advert-v0-bids-recommendations",
        },
        {
          text: "Статистика поисковых кластеров",
          link: "/en/reference/api/promotion/post-adv-v0-normquery-stats",
        },
        {
          text: "Список ставок поисковых кластеров",
          link: "/en/reference/api/promotion/post-adv-v0-normquery-get-bids",
        },
        {
          text: "Конфигурационные значения продвижения",
          link: "/en/reference/api/promotion/get-api-advert-v1-config",
        },
        {
          text: "Установить ставки для поисковых кластеров в валюте аккаунта продавца",
          link: "/en/reference/api/promotion/post-api-advert-v1-normquery-bids",
        },
        {
          text: "Установить ставки для поисковых кластеров",
          link: "/en/reference/api/promotion/post-adv-v0-normquery-bids",
        },
        {
          text: "Удалить ставки поисковых кластеров",
          link: "/en/reference/api/promotion/delete-adv-v0-normquery-bids",
        },
        {
          text: "Список минус-фраз кампаний",
          link: "/en/reference/api/promotion/post-adv-v0-normquery-get-minus",
        },
        {
          text: "Установка и удаление минус-фраз",
          link: "/en/reference/api/promotion/post-adv-v0-normquery-set-minus",
        },
        {
          text: "Количество медиакампаний",
          link: "/en/reference/api/promotion/get-adv-v1-count",
        },
        {
          text: "Список медиакампаний",
          link: "/en/reference/api/promotion/get-adv-v1-adverts",
        },
        {
          text: "Информация о медиакампании",
          link: "/en/reference/api/promotion/get-adv-v1-advert",
        },
        {
          text: "Статистика кампаний",
          link: "/en/reference/api/promotion/get-adv-v3-fullstats",
        },
        {
          text: "Статистика медиакампаний",
          link: "/en/reference/api/promotion/post-adv-v1-stats",
        },
        {
          text: "Список акций",
          link: "/en/reference/api/promotion/get-api-v1-calendar-promotions",
        },
        {
          text: "Детальная информация об акциях",
          link: "/en/reference/api/promotion/get-api-v1-calendar-promotions-details",
        },
        {
          text: "Список товаров для участия в акции",
          link: "/en/reference/api/promotion/get-api-v1-calendar-promotions-nomenclatures",
        },
        {
          text: "Добавить товар в акцию",
          link: "/en/reference/api/promotion/post-api-v1-calendar-promotions-upload",
        },
        {
          text: "Списки активных и неактивных поисковых кластеров",
          link: "/en/reference/api/promotion/post-adv-v0-normquery-list",
        },
        {
          text: "Статистика по поисковым кластерам с детализацией по дням",
          link: "/en/reference/api/promotion/post-adv-v1-normquery-stats",
        },
        {
          text: "Получить настройки дневных лимитов кампаний",
          link: "/en/reference/api/promotion/get-api-advert-v0-daily-limits",
        },
        {
          text: "Настройка дневных лимитов кампаний",
          link: "/en/reference/api/promotion/put-api-advert-v0-daily-limits",
        },
      ],
    },
    {
      text: "Общение с покупателями · communications",
      collapsed: true,
      items: [
        {
          text: "Непросмотренные отзывы и вопросы",
          link: "/en/reference/api/communications/get-api-v1-new-feedbacks-questions",
        },
        {
          text: "Неотвеченные вопросы",
          link: "/en/reference/api/communications/get-api-v1-questions-count-unanswered",
        },
        {
          text: "Количество вопросов",
          link: "/en/reference/api/communications/get-api-v1-questions-count",
        },
        {
          text: "Список вопросов",
          link: "/en/reference/api/communications/get-api-v1-questions",
        },
        {
          text: "Работа с вопросами",
          link: "/en/reference/api/communications/patch-api-v1-questions",
        },
        {
          text: "Получить вопрос по ID",
          link: "/en/reference/api/communications/get-api-v1-question",
        },
        {
          text: "Необработанные отзывы",
          link: "/en/reference/api/communications/get-api-v1-feedbacks-count-unanswered",
        },
        {
          text: "Количество отзывов",
          link: "/en/reference/api/communications/get-api-v1-feedbacks-count",
        },
        {
          text: "Список отзывов",
          link: "/en/reference/api/communications/get-api-v1-feedbacks",
        },
        {
          text: "Ответить на отзыв",
          link: "/en/reference/api/communications/post-api-v1-feedbacks-answer",
        },
        {
          text: "Отредактировать ответ на отзыв",
          link: "/en/reference/api/communications/patch-api-v1-feedbacks-answer",
        },
        {
          text: "Возврат товара по ID отзыва",
          link: "/en/reference/api/communications/post-api-v1-feedbacks-order-return",
        },
        {
          text: "Получить отзыв по ID",
          link: "/en/reference/api/communications/get-api-v1-feedback",
        },
        {
          text: "Список архивных отзывов",
          link: "/en/reference/api/communications/get-api-v1-feedbacks-archive",
        },
        {
          text: "Список закреплённых и откреплённых отзывов",
          link: "/en/reference/api/communications/get-api-feedbacks-v1-pins",
        },
        {
          text: "Закрепить отзывы",
          link: "/en/reference/api/communications/post-api-feedbacks-v1-pins",
        },
        {
          text: "Открепить отзывы",
          link: "/en/reference/api/communications/delete-api-feedbacks-v1-pins",
        },
        {
          text: "Количество закреплённых и откреплённых отзывов",
          link: "/en/reference/api/communications/get-api-feedbacks-v1-pins-count",
        },
        {
          text: "Лимиты закреплённых отзывов",
          link: "/en/reference/api/communications/get-api-feedbacks-v1-pins-limits",
        },
        {
          text: "Список чатов",
          link: "/en/reference/api/communications/get-api-v1-seller-chats",
        },
        {
          text: "События чатов",
          link: "/en/reference/api/communications/get-api-v1-seller-events",
        },
        {
          text: "Отправить сообщение",
          link: "/en/reference/api/communications/post-api-v1-seller-message",
        },
        {
          text: "Получить файл из сообщения",
          link: "/en/reference/api/communications/get-api-v1-seller-download-id",
        },
        {
          text: "Заявки покупателей на возврат",
          link: "/en/reference/api/communications/get-api-v1-claims",
        },
        {
          text: "Ответ на заявку покупателя",
          link: "/en/reference/api/communications/patch-api-v1-claim",
        },
      ],
    },
    {
      text: "Тарифы · rates",
      collapsed: true,
      items: [
        {
          text: "Комиссия по категориям товаров",
          link: "/en/reference/api/rates/get-api-v1-tariffs-commission",
        },
        {
          text: "Тарифы на поставку",
          link: "/en/reference/api/rates/get-api-tariffs-v1-acceptance-coefficients",
        },
        {
          text: "Тарифы для коробов",
          link: "/en/reference/api/rates/get-api-v1-tariffs-box",
        },
        {
          text: "Тарифы для монопаллет",
          link: "/en/reference/api/rates/get-api-v1-tariffs-pallet",
        },
        {
          text: "Тарифы на возврат",
          link: "/en/reference/api/rates/get-api-v1-tariffs-return",
        },
      ],
    },
    {
      text: "Аналитика и данные · analytics",
      collapsed: true,
      items: [
        {
          text: "Статистика карточек товаров за период",
          link: "/en/reference/api/analytics/post-api-analytics-v3-sales-funnel-products",
        },
        {
          text: "Статистика карточек товаров по дням",
          link: "/en/reference/api/analytics/post-api-analytics-v3-sales-funnel-products-history",
        },
        {
          text: "Статистика групп карточек товаров по дням",
          link: "/en/reference/api/analytics/post-api-analytics-v3-sales-funnel-grouped-history",
        },
        {
          text: "Создать отчёт",
          link: "/en/reference/api/analytics/post-api-v2-nm-report-downloads",
        },
        {
          text: "Получить список отчётов",
          link: "/en/reference/api/analytics/get-api-v2-nm-report-downloads",
        },
        {
          text: "Сгенерировать отчёт повторно",
          link: "/en/reference/api/analytics/post-api-v2-nm-report-downloads-retry",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/analytics/get-api-v2-nm-report-downloads-file-downloadid",
        },
        {
          text: "Основная страница",
          link: "/en/reference/api/analytics/post-api-v2-search-report-report",
        },
        {
          text: "Пагинация по группам",
          link: "/en/reference/api/analytics/post-api-v2-search-report-table-groups",
        },
        {
          text: "Пагинация по товарам в группе",
          link: "/en/reference/api/analytics/post-api-v2-search-report-table-details",
        },
        {
          text: "Поисковые запросы по товару",
          link: "/en/reference/api/analytics/post-api-v2-search-report-product-search-texts",
        },
        {
          text: "Заказы и позиции по поисковым запросам товара",
          link: "/en/reference/api/analytics/post-api-v2-search-report-product-orders",
        },
        {
          text: "Остатки на складах WB",
          link: "/en/reference/api/analytics/post-api-analytics-v1-stocks-report-wb-warehouses",
        },
        {
          text: "Остатки на складах продавца",
          link: "/en/reference/api/analytics/post-api-analytics-v1-stocks-report-seller-warehouses",
        },
        {
          text: "Данные по группам",
          link: "/en/reference/api/analytics/post-api-v2-stocks-report-products-groups",
        },
        {
          text: "Данные по товарам",
          link: "/en/reference/api/analytics/post-api-v2-stocks-report-products-products",
        },
        {
          text: "Данные по размерам",
          link: "/en/reference/api/analytics/post-api-v2-stocks-report-products-sizes",
        },
        {
          text: "Данные по складам",
          link: "/en/reference/api/analytics/post-api-v2-stocks-report-offices",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/analytics/post-api-analytics-v2-item-rating",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/analytics/post-api-analytics-v1-order-feed",
        },
      ],
    },
    {
      text: "Отчёты · reports",
      collapsed: true,
      items: [
        {
          text: "Заказы",
          link: "/en/reference/api/reports/get-api-v1-supplier-orders",
        },
        {
          text: "Продажи",
          link: "/en/reference/api/reports/get-api-v1-supplier-sales",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/reports/post-api-v1-analytics-excise-report",
        },
        {
          text: "Создать отчёт",
          link: "/en/reference/api/reports/get-api-v1-warehouse-remains",
        },
        {
          text: "Проверить статус",
          link: "/en/reference/api/reports/get-api-v1-warehouse-remains-tasks-task-id-status",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/reports/get-api-v1-warehouse-remains-tasks-task-id-download",
        },
        {
          text: "Удержания за занижение габаритов упаковки",
          link: "/en/reference/api/reports/get-api-analytics-v1-measurement-penalties",
        },
        {
          text: "Замеры склада",
          link: "/en/reference/api/reports/get-api-analytics-v1-warehouse-measurements",
        },
        {
          text: "Подмены и неверные вложения",
          link: "/en/reference/api/reports/get-api-analytics-v1-deductions",
        },
        {
          text: "Самовыкупы",
          link: "/en/reference/api/reports/get-api-v1-analytics-antifraud-details",
        },
        {
          text: "Маркировка товара",
          link: "/en/reference/api/reports/get-api-v1-analytics-goods-labeling",
        },
        {
          text: "Создать отчёт",
          link: "/en/reference/api/reports/get-api-v1-acceptance-report",
        },
        {
          text: "Проверить статус",
          link: "/en/reference/api/reports/get-api-v1-acceptance-report-tasks-task-id-status",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/reports/get-api-v1-acceptance-report-tasks-task-id-download",
        },
        {
          text: "Создать отчёт",
          link: "/en/reference/api/reports/get-api-v1-paid-storage",
        },
        {
          text: "Проверить статус",
          link: "/en/reference/api/reports/get-api-v1-paid-storage-tasks-task-id-status",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/reports/get-api-v1-paid-storage-tasks-task-id-download",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/reports/get-api-v1-analytics-region-sale",
        },
        {
          text: "Бренды продавца",
          link: "/en/reference/api/reports/get-api-v1-analytics-brand-share-brands",
        },
        {
          text: "Родительские категории бренда",
          link: "/en/reference/api/reports/get-api-v1-analytics-brand-share-parent-subjects",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/reports/get-api-v1-analytics-brand-share",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/reports/get-api-v1-analytics-banned-products-blocked",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/reports/get-api-v1-analytics-goods-return",
        },
        {
          text: "Получить отчёт",
          link: "/en/reference/api/reports/get-api-analytics-v1-item-returns",
        },
      ],
    },
    {
      text: "Документы и бухгалтерия · finances",
      collapsed: true,
      items: [
        {
          text: "Получить баланс продавца",
          link: "/en/reference/api/finances/get-api-v1-account-balance",
        },
        {
          text: "Список отчётов реализации",
          link: "/en/reference/api/finances/post-api-finance-v1-sales-reports-list",
        },
        {
          text: "Детализации к отчётам реализации по ID отчётов",
          link: "/en/reference/api/finances/post-api-finance-v1-sales-reports-detailed-reportid",
        },
        {
          text: "Детализации к отчётам реализации за период",
          link: "/en/reference/api/finances/post-api-finance-v1-sales-reports-detailed",
        },
        {
          text: "Список отчётов об издержках на приём платежей",
          link: "/en/reference/api/finances/post-api-finance-v1-acquiring-list",
        },
        {
          text: "Детализации к отчётам об издержках на приём платежей по ID отчётов",
          link: "/en/reference/api/finances/post-api-finance-v1-acquiring-detailed-reportid",
        },
        {
          text: "Детализации к отчётам об издержках на приём платежей за период",
          link: "/en/reference/api/finances/post-api-finance-v1-acquiring-detailed",
        },
        {
          text: "Категории документов",
          link: "/en/reference/api/finances/get-api-v1-documents-categories",
        },
        {
          text: "Список документов",
          link: "/en/reference/api/finances/get-api-v1-documents-list",
        },
        {
          text: "Получить документ",
          link: "/en/reference/api/finances/get-api-v1-documents-download",
        },
        {
          text: "Получить документы",
          link: "/en/reference/api/finances/post-api-v1-documents-download-all",
        },
      ],
    },
  ],
};
